/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = string;
export type DocumentId = string;
export type Title = string;
export type Author = string[];
export type Publisher = string | null;
/**
 * BCP-47 style labels; minimum supported: id, ar, en, unknown
 */
export type Languages = string[];
export type Description = string | null;
export type Identifier = string | null;
export type SourceFilename = string | null;
export type Id = string;
/**
 * None while chapter detection is incomplete (ungrouped chapter)
 */
export type Title1 = string | null;
export type Level = number;
export type Id1 = string;
/**
 * 1-based source page number
 */
export type Page = number;
/**
 * [x0, y0, x1, y1] in PDF points, diagnostics only
 */
export type Bbox = number[] | null;
export type Lang = string;
/**
 * Script classification. Script matters more than natural language (PRD 8.6).
 */
export type ScriptClass = "Arabic" | "Latin" | "Mixed" | "Numeric" | "Neutral";
/**
 * Inline base direction for blocks and spans.
 */
export type Direction = "ltr" | "rtl";
export type Confidence = number | null;
export type Warnings = string[];
/**
 * True only when a human explicitly edited the content
 */
export type ModifiedByUser = boolean;
export type Score = number;
export type PresentationFormsDetected = boolean;
export type SuspiciousSpacing = boolean;
export type CombiningMarkWarnings = number;
export type BidiWarning = boolean;
/**
 * Word-initial harakat detected: glyph order likely reversed.
 */
export type ReversedOrderSuspected = boolean;
export type Type = "heading";
export type Level1 = number;
export type Text = string;
export type SourceText = string | null;
export type Transformations = string[];
export type Id2 = string;
export type Lang1 = string;
export type Confidence1 = number | null;
export type Warnings1 = string[];
/**
 * True only when a human explicitly edited the content
 */
export type ModifiedByUser1 = boolean;
export type Type1 = "paragraph";
/**
 * @minItems 1
 */
export type Content = [TextNode | SpanNode, ...(TextNode | SpanNode)[]];
export type Type2 = "text";
export type Text1 = string;
/**
 * Original extraction when a transformation was applied
 */
export type SourceText1 = string | null;
/**
 * Applied transformations, e.g. ['dehyphenation']
 */
export type Transformations1 = string[];
export type Type3 = "span";
export type Text2 = string;
export type Lang2 = string;
/**
 * Script classification. Script matters more than natural language (PRD 8.6).
 */
export type ScriptClass1 = "Arabic" | "Latin" | "Mixed" | "Numeric" | "Neutral";
export type SourceText2 = string | null;
export type Transformations2 = string[];
export type Id3 = string;
export type Lang3 = string;
export type Confidence2 = number | null;
export type Warnings2 = string[];
/**
 * True only when a human explicitly edited the content
 */
export type ModifiedByUser2 = boolean;
export type Type4 = "quote";
/**
 * e.g. 'arabic' for Arabic quote blocks
 */
export type Subtype = string | null;
export type Text3 = string;
export type SourceText3 = string | null;
export type Transformations3 = string[];
export type Id4 = string;
export type Lang4 = string;
export type Confidence3 = number | null;
export type Warnings3 = string[];
/**
 * True only when a human explicitly edited the content
 */
export type ModifiedByUser3 = boolean;
export type Type5 = "list";
export type Ordered = boolean;
export type Id5 = string;
export type Lang5 = string;
export type Confidence4 = number | null;
export type Warnings4 = string[];
/**
 * True only when a human explicitly edited the content
 */
export type ModifiedByUser4 = boolean;
export type Type6 = "image";
export type ResourceId = string;
export type Alt = string | null;
export type CaptionBlockId = string | null;
export type Id6 = string;
export type Lang6 = string;
export type Confidence5 = number | null;
export type Warnings5 = string[];
/**
 * True only when a human explicitly edited the content
 */
export type ModifiedByUser5 = boolean;
export type Type7 = "footnote";
export type Marker = string;
export type Id7 = string;
export type Lang7 = string;
export type Confidence6 = number | null;
export type Warnings6 = string[];
/**
 * True only when a human explicitly edited the content
 */
export type ModifiedByUser6 = boolean;
export type Type8 = "table";
export type Text4 = string;
export type Lang8 = string | null;
export type Rows = TableCell[][];
export type FallbackResourceId = string | null;
export type Id8 = string;
export type Lang9 = string;
export type Confidence7 = number | null;
export type Warnings7 = string[];
/**
 * True only when a human explicitly edited the content
 */
export type ModifiedByUser7 = boolean;
export type Type9 = "page_break";
export type Blocks2 = (
  HeadingBlock | ParagraphBlock | QuoteBlock | ListBlock | ImageBlock | FootnoteBlock | TableBlock | PageBreakBlock
)[];
export type Blocks1 = (
  HeadingBlock | ParagraphBlock | QuoteBlock | ListBlock | ImageBlock | FootnoteBlock | TableBlock | PageBreakBlock
)[];
export type Items = ListItem[];
export type Blocks = (
  HeadingBlock | ParagraphBlock | QuoteBlock | ListBlock | ImageBlock | FootnoteBlock | TableBlock | PageBreakBlock
)[];
export type Chapters = Chapter[];
export type Id9 = string;
/**
 * e.g. 'image' or 'font'
 */
export type Kind = string;
export type MediaType = string | null;
export type Filename = string | null;
export type SourcePage = number | null;
/**
 * Encoded payload (base64 in JSON). MVP: images are carried inline so a ReflowDoc JSON is self-contained.
 */
export type Content1 = string | null;
export type Resources = Resource[];
/**
 * Warning code, e.g. READING_ORDER_UNCERTAIN, LOW_ARABIC_CONFIDENCE
 */
export type Code = string;
export type Severity = "info" | "warning" | "error";
export type Message = string;
export type SourcePage1 = number | null;
export type BlockIds = string[];
export type Warnings8 = ReflowWarning[];

export interface ReflowDocument {
  schema_version?: SchemaVersion;
  document_id?: DocumentId;
  metadata?: DocumentMetadata;
  chapters?: Chapters;
  resources?: Resources;
  warnings?: Warnings8;
  [k: string]: unknown;
}
export interface DocumentMetadata {
  title?: Title;
  author?: Author;
  publisher?: Publisher;
  languages?: Languages;
  description?: Description;
  identifier?: Identifier;
  source_filename?: SourceFilename;
  [k: string]: unknown;
}
export interface Chapter {
  id: Id;
  title?: Title1;
  level?: Level;
  blocks?: Blocks;
  [k: string]: unknown;
}
export interface HeadingBlock {
  id: Id1;
  source?: SourceRef | null;
  lang?: Lang;
  script?: ScriptClass | null;
  dir?: Direction | null;
  confidence?: Confidence;
  warnings?: Warnings;
  modified_by_user?: ModifiedByUser;
  /**
   * Arabic diagnostic metadata when the block carries Arabic
   */
  arabic_integrity?: ArabicIntegrity | null;
  type?: Type;
  level?: Level1;
  text: Text;
  source_text?: SourceText;
  transformations?: Transformations;
  [k: string]: unknown;
}
/**
 * Extraction provenance, kept for diagnostics only.
 *
 * Coordinates are PDF points and must never be used by renderers for layout.
 */
export interface SourceRef {
  page: Page;
  bbox?: Bbox;
  [k: string]: unknown;
}
/**
 * Arabic diagnostic metadata attached to blocks/spans when applicable.
 */
export interface ArabicIntegrity {
  score: Score;
  presentation_forms_detected?: PresentationFormsDetected;
  suspicious_spacing?: SuspiciousSpacing;
  combining_mark_warnings?: CombiningMarkWarnings;
  bidi_warning?: BidiWarning;
  reversed_order_suspected?: ReversedOrderSuspected;
  [k: string]: unknown;
}
export interface ParagraphBlock {
  id: Id2;
  source?: SourceRef | null;
  lang?: Lang1;
  script?: ScriptClass | null;
  dir?: Direction | null;
  confidence?: Confidence1;
  warnings?: Warnings1;
  modified_by_user?: ModifiedByUser1;
  /**
   * Arabic diagnostic metadata when the block carries Arabic
   */
  arabic_integrity?: ArabicIntegrity | null;
  type?: Type1;
  content: Content;
  [k: string]: unknown;
}
/**
 * A run of text in the block's primary language/direction.
 */
export interface TextNode {
  type?: Type2;
  text: Text1;
  source_text?: SourceText1;
  transformations?: Transformations1;
  [k: string]: unknown;
}
/**
 * An inline span with its own language/script/direction (mixed-direction text).
 */
export interface SpanNode {
  type?: Type3;
  text: Text2;
  lang?: Lang2;
  script?: ScriptClass1;
  dir?: Direction | null;
  source_text?: SourceText2;
  transformations?: Transformations2;
  arabic_integrity?: ArabicIntegrity | null;
  [k: string]: unknown;
}
export interface QuoteBlock {
  id: Id3;
  source?: SourceRef | null;
  lang?: Lang3;
  script?: ScriptClass | null;
  dir?: Direction | null;
  confidence?: Confidence2;
  warnings?: Warnings2;
  modified_by_user?: ModifiedByUser2;
  /**
   * Arabic diagnostic metadata when the block carries Arabic
   */
  arabic_integrity?: ArabicIntegrity | null;
  type?: Type4;
  subtype?: Subtype;
  text: Text3;
  source_text?: SourceText3;
  transformations?: Transformations3;
  [k: string]: unknown;
}
export interface ListBlock {
  id: Id4;
  source?: SourceRef | null;
  lang?: Lang4;
  script?: ScriptClass | null;
  dir?: Direction | null;
  confidence?: Confidence3;
  warnings?: Warnings3;
  modified_by_user?: ModifiedByUser3;
  /**
   * Arabic diagnostic metadata when the block carries Arabic
   */
  arabic_integrity?: ArabicIntegrity | null;
  type?: Type5;
  ordered?: Ordered;
  items?: Items;
  [k: string]: unknown;
}
export interface ListItem {
  blocks?: Blocks1;
  [k: string]: unknown;
}
export interface ImageBlock {
  id: Id5;
  source?: SourceRef | null;
  lang?: Lang5;
  script?: ScriptClass | null;
  dir?: Direction | null;
  confidence?: Confidence4;
  warnings?: Warnings4;
  modified_by_user?: ModifiedByUser4;
  /**
   * Arabic diagnostic metadata when the block carries Arabic
   */
  arabic_integrity?: ArabicIntegrity | null;
  type?: Type6;
  resource_id: ResourceId;
  alt?: Alt;
  caption_block_id?: CaptionBlockId;
  [k: string]: unknown;
}
export interface FootnoteBlock {
  id: Id6;
  source?: SourceRef | null;
  lang?: Lang6;
  script?: ScriptClass | null;
  dir?: Direction | null;
  confidence?: Confidence5;
  warnings?: Warnings5;
  modified_by_user?: ModifiedByUser5;
  /**
   * Arabic diagnostic metadata when the block carries Arabic
   */
  arabic_integrity?: ArabicIntegrity | null;
  type?: Type7;
  marker: Marker;
  blocks?: Blocks2;
  [k: string]: unknown;
}
export interface TableBlock {
  id: Id7;
  source?: SourceRef | null;
  lang?: Lang7;
  script?: ScriptClass | null;
  dir?: Direction | null;
  confidence?: Confidence6;
  warnings?: Warnings6;
  modified_by_user?: ModifiedByUser6;
  /**
   * Arabic diagnostic metadata when the block carries Arabic
   */
  arabic_integrity?: ArabicIntegrity | null;
  type?: Type8;
  rows?: Rows;
  fallback_resource_id?: FallbackResourceId;
  [k: string]: unknown;
}
export interface TableCell {
  text: Text4;
  lang?: Lang8;
  dir?: Direction | null;
  [k: string]: unknown;
}
export interface PageBreakBlock {
  id: Id8;
  source?: SourceRef | null;
  lang?: Lang9;
  script?: ScriptClass | null;
  dir?: Direction | null;
  confidence?: Confidence7;
  warnings?: Warnings7;
  modified_by_user?: ModifiedByUser7;
  /**
   * Arabic diagnostic metadata when the block carries Arabic
   */
  arabic_integrity?: ArabicIntegrity | null;
  type?: Type9;
  [k: string]: unknown;
}
/**
 * A binary resource referenced by blocks (image, font, table fallback).
 */
export interface Resource {
  id: Id9;
  kind: Kind;
  media_type?: MediaType;
  filename?: Filename;
  source_page?: SourcePage;
  content?: Content1;
  [k: string]: unknown;
}
/**
 * Explicit, non-silent uncertainty (ARCHITECTURE.md section 10).
 */
export interface ReflowWarning {
  code: Code;
  severity?: Severity;
  message: Message;
  source_page?: SourcePage1;
  block_ids?: BlockIds;
  [k: string]: unknown;
}
